sudo: required
services:
  - docker

language: node_js

before_install:
  - docker build -t cabdev/docker-react -f Dockerfile.dev . 

script:
  - docker run cabdev/docker-react npm run test -- --coverage